<a href="https://colab.research.google.com/github/DevendraaK/Machine-Learning-and-Deep-Learning-Projects-/blob/main/numpy_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
a=np.zeros((3,3,3))
print(a)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [ ]:
np.ones((2,2,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [ ]:
np.full((2,2),"hellowdevendra",dtype='<U7')

array([['hellowd', 'hellowd'],
       ['hellowd', 'hellowd']], dtype='<U7')

In [ ]:
np.random.rand(10)

array([0.10572175, 0.61971312, 0.27989047, 0.76645271, 0.80659257,
       0.26249133, 0.76987385, 0.37298183, 0.32365084, 0.69669279])

In [ ]:
data=np.random.randint(5,10,(10,10))
data

array([[5, 7, 7, 9, 7, 6, 9, 6, 6, 9],
       [9, 9, 9, 9, 7, 7, 7, 8, 7, 8],
       [7, 8, 7, 9, 5, 8, 6, 8, 9, 6],
       [7, 8, 5, 6, 6, 6, 6, 5, 5, 6],
       [8, 7, 9, 6, 5, 6, 5, 7, 8, 6],
       [8, 6, 8, 6, 6, 8, 7, 9, 9, 8],
       [9, 8, 7, 6, 7, 9, 9, 8, 9, 8],
       [5, 5, 5, 9, 9, 9, 8, 8, 5, 9],
       [7, 5, 9, 8, 7, 6, 5, 6, 5, 6],
       [9, 7, 8, 8, 7, 8, 6, 6, 6, 7]])

Access of Numpy

In [ ]:
data[4:8]

array([[5, 6, 5, 8, 7, 8, 5, 8, 6, 7],
       [7, 8, 9, 7, 9, 8, 7, 6, 8, 6],
       [8, 6, 7, 8, 5, 5, 6, 9, 8, 8],
       [8, 8, 6, 6, 5, 7, 5, 7, 8, 7]])

In [ ]:
data[4:8,4:6]

array([[7, 8],
       [9, 8],
       [5, 5],
       [5, 7]])

In [ ]:
data[4:6,4:6]

array([[7, 8],
       [9, 8]])

Combine Data

In [ ]:
data1=np.random.randint(5,15,size=(5,3))
print(data1)

[[ 9  5 12]
 [ 9 10  5]
 [12 12 12]
 [ 6  5  7]
 [13  5  6]]


In [ ]:
data2=np.random.randint(5,15,size=(5,3))
data2

array([[ 8,  8,  9],
       [13,  8, 13],
       [ 5, 13, 13],
       [10, 12, 13],
       [ 9, 13, 13]])

In [ ]:
np.hstack([data1,data2])

array([[ 9,  8,  9, 12,  7,  8],
       [11,  5, 10,  8,  6, 13],
       [ 5,  5,  9,  6,  7,  8],
       [ 5,  7, 10, 14, 12,  7],
       [13,  7,  7,  8,  5,  8]])

In [ ]:
np.vstack([data1,data2])

array([[ 9,  5, 12],
       [ 9, 10,  5],
       [12, 12, 12],
       [ 6,  5,  7],
       [13,  5,  6],
       [ 8,  8,  9],
       [13,  8, 13],
       [ 5, 13, 13],
       [10, 12, 13],
       [ 9, 13, 13]])

In [ ]:
np.concatenate([data1,data2],axis=1)

array([[ 9,  5, 12,  8,  8,  9],
       [ 9, 10,  5, 13,  8, 13],
       [12, 12, 12,  5, 13, 13],
       [ 6,  5,  7, 10, 12, 13],
       [13,  5,  6,  9, 13, 13]])

In [ ]:
data1 = np.random.randint(5,15,size=(5,3,2))
data1

array([[[12, 12],
        [ 5, 14],
        [13, 11]],

       [[ 6,  5],
        [10, 10],
        [12,  8]],

       [[10,  9],
        [11,  6],
        [11,  6]],

       [[ 7, 11],
        [ 5, 14],
        [12,  6]],

       [[ 6, 11],
        [ 6,  7],
        [ 7,  6]]])

In [ ]:
data2=np.random.randint(5,15,size=(5,3,2))

In [ ]:
np.concatenate([data1,data2],axis=2)

array([[[12, 12, 12,  8],
        [ 5, 14,  6,  7],
        [13, 11, 13,  6]],

       [[ 6,  5, 14,  5],
        [10, 10,  6,  7],
        [12,  8, 10, 14]],

       [[10,  9, 10, 11],
        [11,  6,  7, 14],
        [11,  6, 14,  7]],

       [[ 7, 11,  9, 10],
        [ 5, 14, 13,  8],
        [12,  6, 13, 10]],

       [[ 6, 11,  5, 13],
        [ 6,  7, 11, 13],
        [ 7,  6,  6,  8]]])

Splitting Data

In [ ]:
a1,a2=np.hsplit(data,[5])

In [ ]:
a1

array([[8, 6, 7, 9, 5],
       [5, 5, 5, 8, 5],
       [8, 9, 8, 5, 6],
       [9, 9, 6, 5, 9],
       [5, 6, 5, 8, 7],
       [7, 8, 9, 7, 9],
       [8, 6, 7, 8, 5],
       [8, 8, 6, 6, 5],
       [7, 9, 7, 8, 5],
       [5, 9, 6, 8, 9]])

In [ ]:
a2

array([[8, 5, 8, 6, 7],
       [5, 9, 6, 9, 7],
       [6, 9, 8, 6, 8],
       [6, 9, 8, 7, 9],
       [8, 5, 8, 6, 7],
       [8, 7, 6, 8, 6],
       [5, 6, 9, 8, 8],
       [7, 5, 7, 8, 7],
       [9, 9, 9, 5, 5],
       [5, 8, 9, 6, 8]])

In [ ]:
b1,b2,b3=np.vsplit(data,[5,7])

In [ ]:
b1

array([[5, 7, 7, 9, 7, 6, 9, 6, 6, 9],
       [9, 9, 9, 9, 7, 7, 7, 8, 7, 8],
       [7, 8, 7, 9, 5, 8, 6, 8, 9, 6],
       [7, 8, 5, 6, 6, 6, 6, 5, 5, 6],
       [8, 7, 9, 6, 5, 6, 5, 7, 8, 6]])

In [ ]:
b2

array([[8, 6, 8, 6, 6, 8, 7, 9, 9, 8],
       [9, 8, 7, 6, 7, 9, 9, 8, 9, 8]])

In [ ]:
b3

array([[5, 5, 5, 9, 9, 9, 8, 8, 5, 9],
       [7, 5, 9, 8, 7, 6, 5, 6, 5, 6],
       [9, 7, 8, 8, 7, 8, 6, 6, 6, 7]])

Shape,Dimension

In [ ]:
data.shape

(10, 10)

In [ ]:
data.ndim

2

In [ ]:
data.size

100

In [ ]:
data.reshape(4,25)

array([[5, 7, 7, 9, 7, 6, 9, 6, 6, 9, 9, 9, 9, 9, 7, 7, 7, 8, 7, 8, 7, 8,
        7, 9, 5],
       [8, 6, 8, 9, 6, 7, 8, 5, 6, 6, 6, 6, 5, 5, 6, 8, 7, 9, 6, 5, 6, 5,
        7, 8, 6],
       [8, 6, 8, 6, 6, 8, 7, 9, 9, 8, 9, 8, 7, 6, 7, 9, 9, 8, 9, 8, 5, 5,
        5, 9, 9],
       [9, 8, 8, 5, 9, 7, 5, 9, 8, 7, 6, 5, 6, 5, 6, 9, 7, 8, 8, 7, 8, 6,
        6, 6, 7]])

In [ ]:
d=np.array([1,2,3,4,5,6,7,9])

In [ ]:
d.ndim

1

In [ ]:
d.shape

(8,)

In [ ]:
d.size

8

In [ ]:
d.reshape(8,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [9]])

In [ ]:
data.reshape(-1,20)

array([[5, 7, 7, 9, 7, 6, 9, 6, 6, 9, 9, 9, 9, 9, 7, 7, 7, 8, 7, 8],
       [7, 8, 7, 9, 5, 8, 6, 8, 9, 6, 7, 8, 5, 6, 6, 6, 6, 5, 5, 6],
       [8, 7, 9, 6, 5, 6, 5, 7, 8, 6, 8, 6, 8, 6, 6, 8, 7, 9, 9, 8],
       [9, 8, 7, 6, 7, 9, 9, 8, 9, 8, 5, 5, 5, 9, 9, 9, 8, 8, 5, 9],
       [7, 5, 9, 8, 7, 6, 5, 6, 5, 6, 9, 7, 8, 8, 7, 8, 6, 6, 6, 7]])

Utility Function

In [ ]:
np.sum(data)

714

In [ ]:
np.sum(data,axis=1)

array([71, 80, 73, 60, 67, 75, 80, 72, 64, 72])

In [ ]:
data

array([[5, 7, 7, 9, 7, 6, 9, 6, 6, 9],
       [9, 9, 9, 9, 7, 7, 7, 8, 7, 8],
       [7, 8, 7, 9, 5, 8, 6, 8, 9, 6],
       [7, 8, 5, 6, 6, 6, 6, 5, 5, 6],
       [8, 7, 9, 6, 5, 6, 5, 7, 8, 6],
       [8, 6, 8, 6, 6, 8, 7, 9, 9, 8],
       [9, 8, 7, 6, 7, 9, 9, 8, 9, 8],
       [5, 5, 5, 9, 9, 9, 8, 8, 5, 9],
       [7, 5, 9, 8, 7, 6, 5, 6, 5, 6],
       [9, 7, 8, 8, 7, 8, 6, 6, 6, 7]])

In [ ]:
np.sin(data)

array([[-0.95892427,  0.6569866 ,  0.6569866 ,  0.41211849,  0.6569866 ,
        -0.2794155 ,  0.41211849, -0.2794155 , -0.2794155 ,  0.41211849],
       [ 0.41211849,  0.41211849,  0.41211849,  0.41211849,  0.6569866 ,
         0.6569866 ,  0.6569866 ,  0.98935825,  0.6569866 ,  0.98935825],
       [ 0.6569866 ,  0.98935825,  0.6569866 ,  0.41211849, -0.95892427,
         0.98935825, -0.2794155 ,  0.98935825,  0.41211849, -0.2794155 ],
       [ 0.6569866 ,  0.98935825, -0.95892427, -0.2794155 , -0.2794155 ,
        -0.2794155 , -0.2794155 , -0.95892427, -0.95892427, -0.2794155 ],
       [ 0.98935825,  0.6569866 ,  0.41211849, -0.2794155 , -0.95892427,
        -0.2794155 , -0.95892427,  0.6569866 ,  0.98935825, -0.2794155 ],
       [ 0.98935825, -0.2794155 ,  0.98935825, -0.2794155 , -0.2794155 ,
         0.98935825,  0.6569866 ,  0.41211849,  0.41211849,  0.98935825],
       [ 0.41211849,  0.98935825,  0.6569866 , -0.2794155 ,  0.6569866 ,
         0.41211849,  0.41211849,  0.98935825

In [ ]:
np.tan(data)

array([[-3.38051501,  0.87144798,  0.87144798, -0.45231566,  0.87144798,
        -0.29100619, -0.45231566, -0.29100619, -0.29100619, -0.45231566],
       [-0.45231566, -0.45231566, -0.45231566, -0.45231566,  0.87144798,
         0.87144798,  0.87144798, -6.79971146,  0.87144798, -6.79971146],
       [ 0.87144798, -6.79971146,  0.87144798, -0.45231566, -3.38051501,
        -6.79971146, -0.29100619, -6.79971146, -0.45231566, -0.29100619],
       [ 0.87144798, -6.79971146, -3.38051501, -0.29100619, -0.29100619,
        -0.29100619, -0.29100619, -3.38051501, -3.38051501, -0.29100619],
       [-6.79971146,  0.87144798, -0.45231566, -0.29100619, -3.38051501,
        -0.29100619, -3.38051501,  0.87144798, -6.79971146, -0.29100619],
       [-6.79971146, -0.29100619, -6.79971146, -0.29100619, -0.29100619,
        -6.79971146,  0.87144798, -0.45231566, -0.45231566, -6.79971146],
       [-0.45231566, -6.79971146,  0.87144798, -0.29100619,  0.87144798,
        -0.45231566, -0.45231566, -6.79971146

In [ ]:
data.T

array([[5, 9, 7, 7, 8, 8, 9, 5, 7, 9],
       [7, 9, 8, 8, 7, 6, 8, 5, 5, 7],
       [7, 9, 7, 5, 9, 8, 7, 5, 9, 8],
       [9, 9, 9, 6, 6, 6, 6, 9, 8, 8],
       [7, 7, 5, 6, 5, 6, 7, 9, 7, 7],
       [6, 7, 8, 6, 6, 8, 9, 9, 6, 8],
       [9, 7, 6, 6, 5, 7, 9, 8, 5, 6],
       [6, 8, 8, 5, 7, 9, 8, 8, 6, 6],
       [6, 7, 9, 5, 8, 9, 9, 5, 5, 6],
       [9, 8, 6, 6, 6, 8, 8, 9, 6, 7]])

In [ ]:
data.mean(axis=1)

array([7.1, 8. , 7.3, 6. , 6.7, 7.5, 8. , 7.2, 6.4, 7.2])

In [ ]:
data.std(axis=1)

array([1.37477271, 0.89442719, 1.26885775, 0.89442719, 1.26885775,
       1.11803399, 1.        , 1.83303028, 1.28062485, 0.9797959 ])

Broadcasting

In [ ]:
v=np.array([1,2,3,4,5])

In [ ]:
s=10

In [ ]:
v+s

array([11, 12, 13, 14, 15])

In [ ]:
t=[10,11]