<a href="https://colab.research.google.com/github/DevendraaK/Machine-Learning-and-Deep-Learning-Projects-/blob/main/Numpy_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
a=[1,2,3,4,5]
print(a)

[1, 2, 3, 4, 5]


In [ ]:
type(a)

list

In [ ]:
a*2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [ ]:
salary = [1000,2000,3000,4000]


In [ ]:
import numpy as np  # Numerical Python

In [ ]:
a = np.array([10,20,30,40])

In [ ]:
print(a)

[10 20 30 40]


In [ ]:
type(a)


numpy.ndarray

In [ ]:
a+200

array([210, 220, 230, 240])

In [ ]:
a-10

array([ 0, 10, 20, 30])

In [ ]:
a*2

array([20, 40, 60, 80])

In [ ]:
a/5

array([2., 4., 6., 8.])

In [ ]:


b= np.array([2,3,4,5,6,7])

In [ ]:
b

array([2, 3, 4, 5, 6, 7])

In [ ]:
b.dtype

dtype('int64')

In [ ]:
b.itemsize

8

In [ ]:
# 1byte = 8bit
# 64 bit = 8 bytes

In [ ]:
b.shape

(6,)

In [ ]:
print(b)

[2 3 4 5 6 7]


In [ ]:
b.shape = (2,3)

In [ ]:
print(b)


[[2 3 4]
 [5 6 7]]


In [ ]:
b.shape

(2, 3)

In [ ]:
b.ndim

2

In [ ]:
b = np.array(a,dtype=np.int16,ndmin=3)


In [ ]:
b

array([[[10, 20, 30, 40]]], dtype=int16)

In [ ]:
b.dtype,b.itemsize,b.shape

(dtype('int16'), 2, (1, 1, 4))

In [ ]:
list(range(1,10))

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
np.arange(0.1,17,0.1)

array([ 0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,  1.1,
        1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,  2.2,
        2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,  3.3,
        3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,  4.4,
        4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,  5.5,
        5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,  6.6,
        6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,  7.7,
        7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,  8.8,
        8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,  9.9,
       10. , 10.1, 10.2, 10.3, 10.4, 10.5, 10.6, 10.7, 10.8, 10.9, 11. ,
       11.1, 11.2, 11.3, 11.4, 11.5, 11.6, 11.7, 11.8, 11.9, 12. , 12.1,
       12.2, 12.3, 12.4, 12.5, 12.6, 12.7, 12.8, 12.9, 13. , 13.1, 13.2,
       13.3, 13.4, 13.5, 13.6, 13.7, 13.8, 13.9, 14. , 14.1, 14.2, 14.3,
       14.4, 14.5, 14.6, 14.7, 14.8, 14.9, 15. , 15

In [ ]:
a= np.arange(1,17)

In [ ]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [ ]:
a.shape

(16,)

In [ ]:
a.dtype

dtype('int64')

In [ ]:
a.reshape((4,4)) # inplace=False

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
print(a)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


In [ ]:
a.resize((4,4)) #inplace=True

In [ ]:
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [ ]:
np.linspace(1,15,10,retstep=True)

(array([ 1.        ,  2.55555556,  4.11111111,  5.66666667,  7.22222222,
         8.77777778, 10.33333333, 11.88888889, 13.44444444, 15.        ]),
 1.5555555555555556)

In [ ]:
np.linspace?

In [ ]:
np.arange(1,16.5555555555555556, 1.5555555555555556)

array([ 1.        ,  2.55555556,  4.11111111,  5.66666667,  7.22222222,
        8.77777778, 10.33333333, 11.88888889, 13.44444444, 15.        ])

In [ ]:
2**np.linspace(1,10,10)

array([   2.,    4.,    8.,   16.,   32.,   64.,  128.,  256.,  512.,
       1024.])

In [ ]:
np.logspace(1,10,10,base=2)

array([   2.,    4.,    8.,   16.,   32.,   64.,  128.,  256.,  512.,
       1024.])

In [ ]:
np.empty((2,3))

array([[3.5049681e-316, 0.0000000e+000, 0.0000000e+000],
       [0.0000000e+000, 0.0000000e+000, 0.0000000e+000]])

In [ ]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.random.rand(3,3)

array([[0.27477157, 0.93988112, 0.31244023],
       [0.58473811, 0.4822611 , 0.5385323 ],
       [0.93849534, 0.5578135 , 0.62710566]])

In [ ]:
np.eye(4,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.random.chisquare(1,20)

array([2.63248043e+00, 2.88468112e+00, 1.30479869e+00, 1.61678116e+00,
       3.26076063e+00, 2.48434300e-04, 5.80686591e-01, 2.29631774e-06,
       2.10874346e-01, 7.39127113e-01, 6.14690790e-02, 9.95152481e-03,
       6.86633034e-02, 2.94294688e-01, 1.49616803e-01, 3.00686570e-01,
       7.96750443e-01, 8.16371504e-01, 7.86215642e-01, 2.32801069e+00])

In [ ]:
a = np.arange(1,17)

In [ ]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [ ]:
a.shape

(16,)

In [ ]:
a.shape = (2,4,2)

In [ ]:
a

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12],
        [13, 14],
        [15, 16]]])

In [ ]:
a.reshape(4,2,2) # return a new array with the shape

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16]]])

In [ ]:
a

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12],
        [13, 14],
        [15, 16]]])

In [ ]:
a.shape = (4,4)

In [ ]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
a.T

array([[ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15],
       [ 4,  8, 12, 16]])

In [ ]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
np.transpose(a)

array([[ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15],
       [ 4,  8, 12, 16]])

In [ ]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
a=np.arange(1,10)
print(a)

[1 2 3 4 5 6 7 8 9]


In [ ]:
a.shape = (1,1,9)

In [ ]:
a

array([[[1, 2, 3, 4, 5, 6, 7, 8, 9]]])

In [ ]:
a.reshape(1,-1)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [ ]:
a.reshape(-1,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [ ]:
a

array([[[1, 2, 3, 4, 5, 6, 7, 8, 9]]])

In [ ]:
a = np.arange(1,17)
a.shape = (4,4)

In [ ]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
#           Row            Column
#a[start:stop+1:step,start:stop+1:step]
a[::,::]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
a[2:3:,1:4:2]

array([[10, 12]])

In [ ]:
a[1:4:2,1:3:1]

array([[ 6,  7],
       [14, 15]])

In [ ]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
a[a%2==0]

array([ 2,  4,  6,  8, 10, 12, 14, 16])

In [ ]:
a[a%2!=0]

array([ 1,  3,  5,  7,  9, 11, 13, 15])

In [ ]:
a[a>5]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [ ]:
a.shape = (2,1,4,2,1)

In [ ]:
a.shape

(2, 1, 4, 2, 1)

In [ ]:
a.T.shape

(1, 2, 4, 1, 2)

In [ ]:
a.shape

(2, 1, 4, 2, 1)

In [ ]:
np.swapaxes(a,0,2).shape

(4, 1, 2, 2, 1)

In [ ]:
a.shape

(2, 1, 4, 2, 1)

In [ ]:
np.rollaxis(a,2,0).shape

(4, 2, 1, 2, 1)

In [ ]:
a

array([[[[[ 1],
          [ 2]],

         [[ 3],
          [ 4]],

         [[ 5],
          [ 6]],

         [[ 7],
          [ 8]]]],



       [[[[ 9],
          [10]],

         [[11],
          [12]],

         [[13],
          [14]],

         [[15],
          [16]]]]])

In [ ]:
a.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [ ]:
a

array([[[[[ 1],
          [ 2]],

         [[ 3],
          [ 4]],

         [[ 5],
          [ 6]],

         [[ 7],
          [ 8]]]],



       [[[[ 9],
          [10]],

         [[11],
          [12]],

         [[13],
          [14]],

         [[15],
          [16]]]]])

In [ ]:
np.ravel(a)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [ ]:
np.ravel?

In [ ]:
x= a.flat

In [ ]:
type(x)

numpy.flatiter

In [ ]:
next(x)

1

In [ ]:
list(x)

[2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]