<a href="https://colab.research.google.com/github/DevendraaK/Machine-Learning-and-Deep-Learning-Projects-/blob/main/Numpy_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
# print(np.__version__)
print(np.show_config())

blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
None


Numpy add function

In [ ]:
import numpy as np
print(np.info(np.add))

None


Numpy Program to test whether none of the elements of a given array is zero

In [ ]:
import numpy as np
x=np.array([1,2,3,4])
# print("Original Array:")
# print(x)


Test if none of the elements of the said array is zero: 
True
Test if none of the elements of the said array is zero
False


Test whether any of the elements of a given array is non-zero

In [ ]:
import numpy as np
x=np.array([0,0,0,0])
# print("Original Array:")
# print(x)
print("Test whether any of the elements of a given array is non-zero")
print(np.any(x))

Test whether any of the elements of a given array is non-zero
False


Numpy program to test a given array element-wise for finiteness(not infinity or not a NUmber

In [ ]:
import numpy as np
a=np.array([1,0,np.nan,np.inf])
print("Original Array")
print(a)

Original Array
[ 1.  0. nan inf]


Numpy Program to test elements-wise for positive or negative elements

In [ ]:
import numpy as np
a=np.array([1,0,np.nan,np.inf])
# print("Original Array:")
# print(a)
print("test element-wise for positive or negative elements")
print(np.isinf(a))

test element-wise for positive or negative elements
[False False False  True]


Numpy program to test element-wise for NaN of a given array

In [ ]:
import numpy as np
a=np.array([1,0,np.nan,np.inf])
# print("Originnal Array")
# print(a)
print("Test element-wise for NaN:")
print(np.isnan(a))


Test element-wise for NaN:
[False False  True False]


Numpy Program to test element-wise for complex number,real number of a given array.

In [ ]:
import numpy as np
a=np.array([1+1j,1+0j,4.5,3,2,2j])
# print("Original Array")
# print("Checking for complex number:")
# print(np.iscomplex(a))
# print("Checking for real number:")
# print(np.isreal(a))
print("Checking for scalar type:")
print(np.isscalar(3.1))
print(np.isscalar([3.1]))


Checking for scalar type:
True
False


NumPy program to test whether two arrays are element-wise equal within a tolerance

In [ ]:
import numpy as np
print("Test if two arrays are element-wise equal within a tolerance:")
print((np.allclose([1e10,1e-7], [1.00001e10,1e-8])))
print(np.allclose([1e10,1e-8], [1.00001e10,1e-9]))
print(np.allclose([67],[67]))

Test if two arrays are element-wise equal within a tolerance:
False
True
True


program to create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays.

In [ ]:
import numpy as np
x=np.array([3,5])
y=np.array([2,5])
# print("Original Numbers:")
# print(x)
# print(y)
# print(np.greater(x,y))
# print(np.greater_equal(x,y))



[ True False]
[ True  True]


NumPy program to create an element-wise comparison (equal, equal within a tolerance) of two given arrays.

In [ ]:
import numpy as np
x=np.array([72,79,85,90,150,-135,120,-10,60,100])
y=np.array([72,79,85,90,150,-135,120,-10,60,100.001])
print("Original Array:")
print(x)
print(y)
print("Comparison-equal")
print(np.equal(x,y))
print("Comparison -equal within a toelrence")
print(np.allclose(x,y))


Original Array:
[  72   79   85   90  150 -135  120  -10   60  100]
[  72.      79.      85.      90.     150.    -135.     120.     -10.
   60.     100.001]
Comparison-equal
[ True  True  True  True  True  True  True  True  True False]
Comparison -equal within a toelrence
True


NumPy program to create an element-wise comparison (equal, equal within a tolerance) of two given arrays.

In [ ]:
import numpy as np
X=np.array([1,7,13,105])
print("Original Array:")
print(X)
print("%d bytes" % (X.size * X.itemsize))

Original Array:
[  1   7  13 105]
32 bytes


NumPy program to create an array of 10 zeros, 10 ones, 10 fives.

In [ ]:
import numpy as np
array=np.zeros(10)
print("An array of 10 zeros:")
print(array)
array=np.ones(10)
print("An array of 10 ones:")
print(array)
array=np.ones(10)*5
print("An array of 10 fives")
print(array)

An array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
An array of 10 ones:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
An array of 10 fives
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


NumPy program to create an array of 10 zeros, 10 ones, 10 fives.

In [ ]:
import numpy as np
array=np.arange(30,71)
print("Array of the integers from 30 to 70")
print(array)

Array of the integers from 30 to 70
[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


 NumPy program to create a 3x3 identity matrix

In [ ]:
import numpy as np
array_2D=np.identity(3)
print('3*3 matrix:')
print(array_2D)

3*3 matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


NumPy program to create an array of all the even integers from 30 to 70.

In [ ]:
import numpy as np
array=np.arange(30,71,2)
print("Array of all the even integers from 30 to 70:")
print(array)

Array of all the even integers from 30 to 70:
[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


NumPy program to generate a random number between 0 and 1

In [ ]:
import numpy as np
rand